### ISSUE TITLE
Keine verbindung zu E3DC

### ISSUE THREAD

**Issue by 61stephan** [AWhiteKnight/ioBroker.e3dc#6]
Hallo der Adapter verbindet sich nicht mit der E3DC .
 Habe Ip und Rscp Passwort eingetragen mus ich sonst noch etwas machen
 Gruß Stephan

**Comment by AWhiteKnight** [comment]
E3DC verwendet einen Verschlüsselungsalgorithmus mit einem "Fehler", er ist deshalb nicht kompatibel zu den (standardkonformen) JavaScript-Implementierungen. Daher kann der Adapter keine Verbindung aufbauen.
Die Adapter-Entwicklung ist deshalb momentan ausgesetzt.
